language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:setup
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec spec --format Fuubar --color
addons:
  postgresql: "9.3"
services:
  - redis-server