# Environment variables use by the application.
# Set your own values for each variable as needed for development.
# Copy this file to config/application.yml and these settings will be auto loaded.


development:
##### GitHub Settings #####
# Go to: https://github.com/settings/applications/new
# name: whaver
# url: http://localhost:4000
# call back: http://localhost:4000/auth/github/callback

  GITHUB_CLIENT_ID: ''
  GITHUB_SECRET: ''

  # Email Settings
  MANDRILL_USER: 'user@example.com'
  MANDRILL_PASS: ''
  MANDRILL_DOMAIN: 'scrumbot.io'

  # Used for encrypting connection tokens
  ENCRYPTION_KEY: 'something_long_and_complex_and_secret'

  # Used for user login
  DEVISE_SECRET_KEY: 'something_long_and_secret'

  # Get these values by creating a twitter application
  TWITTER_CONSUMER_KEY: ''
  TWITTER_CONSUMER_SECRET: ''