development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: scrumlogs_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: scrumlogs_test
  pool: 5
  username: postgres
  password: 