development:
  adapter: postgresql
  encoding: unicode
  database: scrumlogs_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: scrumlogs_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: scrumlogs_production
  pool: 5
  username: postgres
  password:
